In [69]:
import pandas as pd
from pathlib import Path
from datetime import datetime, timedelta
import time

In [4]:
data_dir = Path("../testtask/test_data/")

In [7]:
list(data_dir.iterdir())

[WindowsPath('../testtask/test_data/t_branches.csv'),
 WindowsPath('../testtask/test_data/t_cities.csv'),
 WindowsPath('../testtask/test_data/t_products.csv'),
 WindowsPath('../testtask/test_data/t_sales.csv')]

In [57]:
df_branches = pd.read_csv(data_dir / "t_branches.csv").drop("Unnamed: 0", axis="columns")
df_cities = pd.read_csv(data_dir / "t_cities.csv").drop("Unnamed: 0", axis="columns")
df_products = pd.read_csv(data_dir / "t_products.csv").drop("Unnamed: 0", axis="columns")
df_sales = pd.read_csv(data_dir / "t_sales.csv").drop("Unnamed: 0", axis="columns")

In [58]:
df_branches

,Ссылка,Наименование,Город,КраткоеНаименование,Регион
0,3841b923-ef12-11dc-bced-00151716f9f5,Кра Склад,2b042b0d-c493-11dc-bf69-00151716f9f5,Кра Склад,ДальнийВостокИВосточнаяСибирь
1,96fc76b4-7955-49ca-8d34-5b173b6f4b01,Улан-Удэ Корпоратив,4f7a40b0-6b0f-11dc-a590-00151716f9f5,Улан-Удэ Корпоратив,ДальнийВостокИВосточнаяСибирь
2,039ae664-7928-4ae4-abd0-935d24d1f642,яКиров Свободы,4186730a-779c-11e0-80d3-001517c526f0,свободы,ВерхнеВолжский
3,f60f5d7b-6ed8-431c-a020-ac50d6d8cd7e,яКазань Московский,55506b55-0565-11df-9cf0-00151716f9f5,ДНС Бытовой на Московском,ВерхнеВолжский
4,3dff0b25-9a0a-401e-9d05-0334cb21fe42,Белгород ТЦ Пассаж,ec54f012-3053-11e1-ae41-001517c526f0,"ТЦ ""Пассаж""",Черноземье
...,...,...,...,...,...
284,0508afa7-992b-11de-8bef-00151716f9f5,Чита Корпоратив,abd61be3-0f84-11de-8383-00151716f9f5,Чита Корпоратив,ДальнийВостокИВосточнаяСибирь
285,6358bdc3-83e7-4e19-8e7b-66ff81b985ec,Омск Корпоратив,ed377842-e7a8-11dd-aaaf-00151716f9f5,Омск Корпоратив,Сибирь
286,3665decf-b1c3-4dba-b3df-9cd665b6ea2e,Тула Корпоратив,c64ded12-080e-11e0-b1fe-001517c526f0,Тула Корпоратив,Черноземье
287,51ab3416-ddc9-44f2-ab5c-2c7e79eaa672,Самара Склад,55506b53-0565-11df-9cf0-00151716f9f5,Самара Склад,СреднеВолжский
288,c176556d-8bab-11de-b404-00151716f9f5,яБлаговещенск Зейская,ca246032-0759-11dc-95ee-00151716f9f5,"""На Зейской""",ДальнийВостокИВосточнаяСибирь

In [59]:
# [x.head(3) for x in [df_branches, df_cities, df_products, df_sales]]
df_products.head(3)

,Ссылка,Наименование
0,2c8a627d-7024-11de-9e32-0015174d2501,Кронштейн 40см.
1,498aefa0-59bd-11e0-b259-001517c526f0,Плеер DVD/MP3/MP4(DivX) Samsung DVD-D530 [HDMI...
2,6fdca235-b7e5-11e0-b04a-00155d030b07,"Смартфон Nokia C5-00.2 2.2"" 270Mb Black 1x0.6G..."

In [60]:
df_sales.head(3)

,Период,Филиал,Номенклатура,Количество,Продажа
0,2012-01-04 18:08:19,7080ffe3-e48e-46ab-882b-47d4d2146737,b90d9481-8766-11e0-bdeb-00155d030b07,1.0,485.0
1,2012-01-11 17:17:08,995135eb-2c57-11dd-900f-00151716f9f5,ce106c89-fe54-11de-b2fc-00151716f9f5,1.0,590.0
2,2012-01-03 14:07:10,8822e357-e9be-4789-8f69-092344105a6b,eac2aa80-272b-11df-b750-001517c526f1,1.0,95.0

In [61]:
df_names_sales = df_sales.merge(right=df_products, left_on="Номенклатура", right_on="Ссылка").drop("Ссылка", axis="columns")
df_names_sales.head(3)

,Период,Филиал,Номенклатура,Количество,Продажа,Наименование
0,2012-01-04 18:08:19,7080ffe3-e48e-46ab-882b-47d4d2146737,b90d9481-8766-11e0-bdeb-00155d030b07,1.0,485.0,Память USB 2.0 Flash Verbatim 8 Gb Netbook/Black
1,2012-01-11 17:17:08,995135eb-2c57-11dd-900f-00151716f9f5,ce106c89-fe54-11de-b2fc-00151716f9f5,1.0,590.0,Память USB 2.0 Flash Transcend 8 Gb JetFlash 6...
2,2012-01-03 14:07:10,8822e357-e9be-4789-8f69-092344105a6b,eac2aa80-272b-11df-b750-001517c526f1,1.0,95.0,Чернила Colouring для устройств Canon/Epson/HP...

In [100]:
a = df_names_sales['Период']
# a.apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S"))
df_names_sales['Период'] = pd.to_datetime(a, yearfirst=True)

In [101]:
df_names_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7964086 entries, 0 to 7964085
Data columns (total 6 columns):
 #   Column        Dtype
---  ------        -----
 0   Период        datetime64[ns]
 1   Филиал        object
 2   Номенклатура  object
 3   Количество    float64
 4   Продажа       float64
 5   Наименование  object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 364.6+ MB

In [105]:
df_names_sales[df_names_sales['Количество'] > 1].sort_values('Количество', ascending=False)

,Период,Филиал,Номенклатура,Количество,Продажа,Наименование
3256249,2012-03-05 14:41:21,9a0d7068-eb3f-11dd-bc0a-00151716f9f5,46d03f88-bba3-11da-ab47-0002b3552d75,1830.0,20130.0,"Кабель UTP, 4 пары, одножильный (solid), кат. ..."
6859505,2012-04-13 10:30:46,9a0d7068-eb3f-11dd-bc0a-00151716f9f5,46d03f88-bba3-11da-ab47-0002b3552d75,1830.0,20130.0,"Кабель UTP, 4 пары, одножильный (solid), кат. ..."
6859502,2012-04-11 17:22:33,9a0d7068-eb3f-11dd-bc0a-00151716f9f5,46d03f88-bba3-11da-ab47-0002b3552d75,1525.0,15768.5,"Кабель UTP, 4 пары, одножильный (solid), кат. ..."
1871789,2012-03-07 15:22:58,13a9c13b-f53e-4997-a428-38d7a02b7353,46d03f88-bba3-11da-ab47-0002b3552d75,1525.0,7625.0,"Кабель UTP, 4 пары, одножильный (solid), кат. ..."
3916688,2012-03-15 14:49:02,96fc76b4-7955-49ca-8d34-5b173b6f4b01,46d03f88-bba3-11da-ab47-0002b3552d75,1220.0,13420.0,"Кабель UTP, 4 пары, одножильный (solid), кат. ..."
...,...,...,...,...,...,...
7963877,2012-04-12 17:02:52,995135eb-2c57-11dd-900f-00151716f9f5,fe13f623-25fc-11e1-ab36-001517c526f0,2.0,21980.0,Office [0141175] Core i3-2100 (3.1 GHz)/2GB/25...
7963892,2012-04-28 18:53:05,804bcf29-a7b7-11dd-8085-00151716f9f5,46d03f84-bba3-11da-ab47-0002b3552d75,2.0,280.0,Патч-корд UTP кат. 5/5e. Длина 10m
7963991,2012-04-25 17:26:16,e790cb6c-a994-45c2-a827-aed1bf318d78,58b5e28d-dfb9-11de-9339-00151716f9f5,2.0,240.0,"Аккумулятор Космос ""AAA"" 1000mAh 1.2V Ni-Mh [R..."
7964037,2012-04-11 12:26:58,48f90773-962c-4838-b3ef-4a4b89e2c661,d0786601-bba2-11da-ab47-0002b3552d75,2.0,320.0,Вентилятор ZALMAN для корпуса 92x92 [ZM-F2] (...
6927986,2012-04-16 18:03:35,ffccc9e9-55b2-11db-acd3-00173147c81e,d81aab38-8663-11e0-bc98-00155d030b07,2.0,15998.0,Смартфон Philips Xenium V816 Black 416MHz/GSM/...

In [106]:
df_names_sales['price_by_unit'] = df_names_sales['Продажа'] / df_names_sales['Количество']

In [108]:
df_names_sales.sort_values("price_by_unit")

,Период,Филиал,Номенклатура,Количество,Продажа,Наименование,price_by_unit
7925199,2012-04-08 12:02:14,36b6f16d-560b-11dc-9c07-00151716f9f5,8c0826ac-f47b-11e0-b3d5-001517c526f0,0.0,-1300.00,"7"" Планшетный ПК Samsung Galaxy Tab 7.0 Plus 1...",-inf
6731774,2012-04-05 19:02:30,024891a5-499c-11dd-8301-00151716f9f5,4ec3d2b1-026c-11e0-879e-001517c526f0,0.0,-200.00,"14.1"" Сумка AirTone AT-W714 Black, нейлон, черный",-inf
6120204,2012-04-23 18:28:53,f38199c6-bb37-4d31-8b4a-aabb47368960,8b4d7d6a-0c0f-11e1-ba09-001517c526f0,0.0,-2300.00,"Смартфон HTC Sensation 4.3"" 1Gb White 2x1.2Ghz...",-inf
617916,2012-02-09 18:49:05,08d7cb9d-c8f4-4d04-88b7-0dbb56d8d30e,21b1aaa8-7847-11df-af3b-001517c526f1,0.0,-100.00,Мышь проводная Microsoft Optical Mouse 200 Bla...,-inf
3592099,2012-02-22 12:46:45,5b855214-0c45-4176-b3f8-ba9f5ce4f08d,26a49ff9-c7c4-11e0-b984-001517c526f0,0.0,-19.40,Процессор Intel Core i3-2130 3.4GHz 3Mb 2xDDR...,-inf
...,...,...,...,...,...,...,...
4287976,2012-03-15 01:00:16,01ca53bf-ff02-11dd-a0a4-00151716f9f5,983d2224-9a89-4f83-991e-5e240251d3c5,0.0,403.93,Обработка грузов на РРЦ,inf
2338062,2012-03-15 06:57:26,51ab3416-ddc9-44f2-ab5c-2c7e79eaa672,983d2224-9a89-4f83-991e-5e240251d3c5,0.0,13.67,Обработка грузов на РРЦ,inf
2338061,2012-03-15 06:54:29,51ab3416-ddc9-44f2-ab5c-2c7e79eaa672,983d2224-9a89-4f83-991e-5e240251d3c5,0.0,10.39,Обработка грузов на РРЦ,inf
2338188,2012-03-15 08:33:03,51ab3416-ddc9-44f2-ab5c-2c7e79eaa672,983d2224-9a89-4f83-991e-5e240251d3c5,0.0,203.92,Обработка грузов на РРЦ,inf
2338187,2012-03-15 06:55:44,51ab3416-ddc9-44f2-ab5c-2c7e79eaa672,983d2224-9a89-4f83-991e-5e240251d3c5,0.0,227.64,Обработка грузов на РРЦ,inf